title: Gemma Li
description: Portfolio
baseurl: ""
url: "https://azurestocking.github.io"

markdown: kramdown
permalink: pretty

collections:
  projects:
    output: true
    permalink: /project/:title/

defaults:
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - .DS_Store 