title: Azure Stocking
description: Personal portfolio website
baseurl: ""
url: "https://azurestocking.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  projects:
    output: true
    permalink: /project/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "project"
      type: "pages"
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - .DS_Store 