title: Gemma Li
description: Portfolio
baseurl: ""
url: "https://azurestocking.github.io"

markdown: kramdown
permalink: pretty

collections:
  projects:
    output: true
    permalink: /project/:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "project"
      type: "pages"
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - .DS_Store 